### ISSUE TITLE
Chore: Create contributing workflow

### ISSUE THREAD

**Issue by therobinkim** [Feedbackr/Feedbackr#5]
@batwood001 assigning to you to get your thoughts. Feel free to assign back to me if solving this issue isn't very interesting to you

I've yet to start working on the codebase; we can start our git commit history from scratch? Also, I'd like to see what your thoughts are on using the conventions listed here: http://karma-runner.github.io/0.8/dev/git-commit-msg.html

**Comment by therobinkim** [comment]
And since we're using Waffle, we can even close/connect issues via our commit messages and PRs! https://github.com/waffleio/waffle.io/wiki/FAQs#prs-and-issues

**Comment by batwood001** [comment]
Those commit message formats seem cumbersome to me. I like the 'Closes ###' feature though... Can we use just that?
